# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 118baf0cf75510eb8aabfe419330ed2b2a4acdf10375f8ba35f90133901fafdaf0a0964f1c2d1d32a7ea8763fd78750e5d016b2d5e7047e2fbca6d732e9d21a6

test:
  secret_key_base: 0ed369219f16209f880c99b50185bae1807f546a5c27ece5eb861aca77e29f60ae5ba3be96e4c229fe3df135695be1fc5e51b555b4c7778c2b9e75221a764a7f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
